### ISSUE TITLE
change background wallpaper?

### ISSUE THREAD

**Issue by trcrsired** [minht11/local-music-pwa#40] opened 2024-08-07 20:08 UTC

**Comment by minht11** [comment] 2024-08-08 16:06
Wallpaper of what? You want to change artwork of the song? If that is true, do you want it to be saved into song file by modifying it or just inside the app memory?

**Comment by trcrsired** [comment] 2024-08-08 17:14
> Wallpaper of what? You want to change artwork of the song? If that is true, do you want it to be saved into song file by modifying it or just inside the app memory?

the app ui

**Comment by minht11** [comment] 2024-08-08 19:28
Essentially duplicate of https://github.com/minht11/local-music-pwa/issues/34

**Closed by minht11** 2024-08-08 19:28 UTC
